# Name that appears on the workflow
# Note: Below you will see ${{ github }} and the github variable used. The former is an env from GitHub actions and the latter is an object argument of the actions/github-script@v4 workflow. These two are not the same and should not be treated as such!
name: Test Conditionals
on:
  pull_request:
    types: [opened, edited]
    branches:
      - 'gh-pages'
      - 'refactor-gh-actions'
  issues:
    types: [opened]
jobs:
  PR-Opened:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened'}}
    steps:
      - name: Output to terminal
        uses: actions/github-script@v4
        # Escapes user input for injection attacks
        env:
          BODY: ${{ github.event.pull_request.body }}
          PRNUMBER: ${{ github.event.number }}
        # Variable that stores result of script
        id: pr-opened
        with:
          script: |
            console.log('Pull request opened')
  PR-Edited:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'edited'}}
    steps:
      - name: Output to terminal
        uses: actions/github-script@v4
        # Escapes user input for injection attacks
        env:
          BODY: ${{ github.event.pull_request.body }}
          PRNUMBER: ${{ github.event.number }}
        # Variable that stores result of script
        id: pr-edited
        with:
          script: |
            console.log('Pull request edited')
            return 'PR edited'

        # Create an artifact with the results of the script
      - name: Create Artifacts
        # Escapes user input for injection attacks
        env:
          ARTIFACT: ${{ steps.pr-edited.outputs.result }}
        run: |
          mkdir -p testConditionals/artifact
          echo ${{ env.ARTIFACT }} > testConditionals/artifact/artifact-pr-edited.txt
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-conditionals-artifact
          path: testConditionals/artifact/

  PR-Opened-Or-Edited:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'edited' || github.event.action == 'opened')}}
    steps:
      - name: Output to terminal
        uses: actions/github-script@v4
        # Escapes user input for injection attacks
        env:
          BODY: ${{ github.event.pull_request.body }}
          PRNUMBER: ${{ github.event.number }}
        # Variable that stores result of script
        id: pr-opened-or-edited
        with:
          script: |
            console.log('Pull request opened or edited')
            return 'PR opened OR edited'

        # Create an artifact with the results of the script
      - name: Create Artifacts
        # Escapes user input for injection attacks
        env:
          ARTIFACT: ${{ steps.pr-opened-or-edited.outputs.result }}
        run: |
          mkdir -p testConditionals/artifact
          echo ${{ env.ARTIFACT }} > testConditionals/artifact/artifact-pr-opened-or-edited.txt
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-conditionals-artifact
          path: testConditionals/artifact/

  Issue-Opened:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened'}}
    steps:
      - name: Output to terminal
        uses: actions/github-script@v4
        # Escapes user input for injection attacks
        env:
          BODY: ${{ github.event.pull_request.body }}
          PRNUMBER: ${{ github.event.number }}
        # Variable that stores result of script
        id: issues-opened
        with:
          script: |
            console.log('Issue opened')
            