# Name that appears on the workflow
# Note: This workflow runs once Add Linked Issue Labels to Pull Request is completed
name: WR Test Conditionals
on:
  workflow_run:
    workflows: ["Test Conditionals"]
    types: [completed]

jobs:
  Last-Workflow-Success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v4
        with:
          script: |
            // Retrieve metadata about the artifacts of the last workflow
            // https://octokit.github.io/rest.js/v18#actions-list-workflow-run-artifacts
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            console.log('array: ', artifacts.data.artifacts)
            const artifactData = artifacts.data.artifacts[0]
            console.log('artifact data: ', artifactData)
            
            // Download artifact with GET API
            // https://octokit.github.io/rest.js/v18#actions-download-artifact
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: artifactData.id,
               archive_format: 'zip',
            });
            const fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/artifact.zip', Buffer.from(download.data));
      - run: unzip artifact.zip

      - name: Read data from artifact
        uses: actions/github-script@v4
        # Variable that stores result of script
        id: labels-result
        with:
          script: |
            // Retrieve pull request and issue number from downloaded artifact
            const fs = require('fs')
            const artifact1 = fs.readFileSync('artifact-pr-edited.txt')
            console.log(artifact1)
            const artifact2 = fs.readFileSync('artifact-pr-opened-or-edited.txt')
            console.log(artifact2)
          
  Last-Workflow-Failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failed Run
        run: echo "The previous GitHub Action failed. Please check the logs for the previous action."